# Add GUI configuration settings

# Display settings
WINDOW_TITLE = "Project CIVILIZATION"
WINDOW_WIDTH = 1280
WINDOW_HEIGHT = 720
FULLSCREEN = False

# Graphics settings
ENABLE_3D = True
RENDER_QUALITY = "Medium"  # Low, Medium, High
ANIMATION_SPEED = 1.0
VSYNC = True

# Camera settings
CAMERA_START_HEIGHT = 10
CAMERA_MIN_HEIGHT = 2
CAMERA_MAX_HEIGHT = 20
CAMERA_ROTATION_SPEED = 1.0
CAMERA_ZOOM_SPEED = 0.5

# UI settings
UI_SCALE = 1.0
FONT_SIZE = 12
SHOW_TOOLTIPS = True
TOOLTIP_DELAY = 0.5  # seconds

# Sound settings
ENABLE_SOUND = True
MUSIC_VOLUME = 0.7
SFX_VOLUME = 0.8

